# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: |
        if [ -d ".next/" ]; then
          rm -rf "sudo rm -r .next/"
        fi
    - run: |
        if [ -d "node_modules/" ]; then
          rm -rf "sudo rm -r node_modules/"
        fi
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo npm install --force
    - run: sudo npm run build --if-present
    - run: sudo pm2 kill
    - run: sudo pm2 start npm --name "next-app" -- run start
